Started GET "/" for 172.21.0.1 at 2022-02-20 15:33:55 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.21.0.1 at 2022-02-20 15:33:55 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.22.0.1 at 2022-02-20 15:37:32 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.22.0.1 at 2022-02-20 15:37:32 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.22.0.1 at 2022-02-20 15:39:43 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.22.0.1 at 2022-02-20 15:39:43 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.22.0.1 at 2022-02-20 15:39:45 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.22.0.1 at 2022-02-20 15:39:45 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.22.0.1 at 2022-02-20 15:39:46 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.22.0.1 at 2022-02-20 15:39:46 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.22.0.1 at 2022-02-20 15:39:55 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.22.0.1 at 2022-02-20 15:39:55 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.23.0.1 at 2022-02-20 15:42:44 +0900
Started GET "/" for 172.23.0.1 at 2022-02-20 15:42:44 +0900
Started GET "/" for 172.23.0.1 at 2022-02-20 15:42:44 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.23.0.1 at 2022-02-20 15:42:45 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.23.0.1 at 2022-02-20 15:42:45 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.23.0.1 at 2022-02-20 15:42:46 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.23.0.1 at 2022-02-20 15:43:47 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.23.0.1 at 2022-02-20 15:43:47 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.23.0.1 at 2022-02-20 15:53:57 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.23.0.1 at 2022-02-20 15:53:57 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 172.23.0.1 at 2022-02-20 15:54:27 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 172.23.0.1 at 2022-02-20 15:54:29 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 172.23.0.1 at 2022-02-20 15:54:31 +0900
  
Mysql2::Error::ConnectionError (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.24.0.1 at 2022-02-20 16:04:36 +0900
  
Mysql2::Error::ConnectionError (Unknown MySQL server host 'mydb' (-2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.24.0.1 at 2022-02-20 16:04:36 +0900
  
Mysql2::Error::ConnectionError (Unknown MySQL server host 'mydb' (-2)):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.24.0.1 at 2022-02-20 16:05:17 +0900
  
Mysql2::Error::ConnectionError (Access denied for user 'user'@'%' to database 'donedeno_development'):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.24.0.1 at 2022-02-20 16:05:18 +0900
  
Mysql2::Error::ConnectionError (Access denied for user 'user'@'%' to database 'donedeno_development'):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
  [1m[35m (0.4ms)[0m  [1m[35mCREATE DATABASE `donedeno_development` DEFAULT CHARACTER SET `utf8mb4`[0m
Started GET "/" for 172.25.0.1 at 2022-02-20 16:11:08 +0900
  
Mysql2::Error::ConnectionError (Access denied for user 'user'@'%' to database 'donedeno_development'):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.25.0.1 at 2022-02-20 16:11:09 +0900
  
Mysql2::Error::ConnectionError (Access denied for user 'user'@'%' to database 'donedeno_development'):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.25.0.1 at 2022-02-20 16:12:06 +0900
  
ActiveRecord::NoDatabaseError (Unknown database 'donedeno_development'):
  
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:28:in `rescue in mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:14:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.25.0.1 at 2022-02-20 16:12:06 +0900
  
ActiveRecord::NoDatabaseError (Unknown database 'donedeno_development'):
  
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:28:in `rescue in mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:14:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.25.0.1 at 2022-02-20 16:14:34 +0900
  
ActiveRecord::NoDatabaseError (Unknown database 'donedeno_development'):
  
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:28:in `rescue in mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:14:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.25.0.1 at 2022-02-20 16:14:35 +0900
  
ActiveRecord::NoDatabaseError (Unknown database 'donedeno_development'):
  
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:28:in `rescue in mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:14:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.25.0.1 at 2022-02-20 16:14:37 +0900
  
ActiveRecord::NoDatabaseError (Unknown database 'donedeno_development'):
  
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:28:in `rescue in mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:14:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.25.0.1 at 2022-02-20 16:14:37 +0900
  
ActiveRecord::NoDatabaseError (Unknown database 'donedeno_development'):
  
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:28:in `rescue in mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/mysql2_adapter.rb:14:in `mysql2_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.4.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.4.6) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.4.6) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.6) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
  [1m[35m (6.8ms)[0m  [1m[35mCREATE DATABASE `donedeno_development` DEFAULT CHARACTER SET `utf8mb4`[0m
  [1m[35m (10.1ms)[0m  [1m[35mCREATE DATABASE `donedeno_test` DEFAULT CHARACTER SET `utf8mb4`[0m
Started GET "/" for 172.25.0.1 at 2022-02-20 16:15:26 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.4.6/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.4.6/lib/rails/templates/rails/welcome/index.html.erb (Duration: 13.4ms | Allocations: 290)
Completed 200 OK in 36ms (Views: 24.7ms | ActiveRecord: 0.0ms | Allocations: 1504)


Started GET "/favicon.ico" for 172.25.0.1 at 2022-02-20 16:15:26 +0900
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.25.0.1 at 2022-02-20 16:15:30 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.4.6/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.4.6/lib/rails/templates/rails/welcome/index.html.erb (Duration: 7.3ms | Allocations: 179)
Completed 200 OK in 12ms (Views: 10.9ms | ActiveRecord: 0.0ms | Allocations: 729)


Started GET "/ws" for 172.25.0.1 at 2022-02-20 16:15:40 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 172.25.0.1 at 2022-02-20 16:15:41 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 172.25.0.1 at 2022-02-20 16:15:43 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 172.25.0.1 at 2022-02-20 16:15:48 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 172.25.0.1 at 2022-02-20 16:15:58 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 172.25.0.1 at 2022-02-20 16:16:16 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.25.0.1 at 2022-02-20 16:16:35 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.4.6/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.4.6/lib/rails/templates/rails/welcome/index.html.erb (Duration: 8.8ms | Allocations: 290)
Completed 200 OK in 35ms (Views: 24.4ms | ActiveRecord: 0.0ms | Allocations: 1504)


Started GET "/ws" for 172.25.0.1 at 2022-02-20 16:16:52 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 172.25.0.1 at 2022-02-20 16:16:53 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 172.25.0.1 at 2022-02-20 16:16:56 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.6) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.6) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.4.6) lib/rails/engine.rb:527:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
